apiVersion: v1
kind: Pod
metadata:
  name: logging-pod-1
spec:
  containers:
    - name: logging
      image: docker.io/library/ubuntu@sha256:20fa2d7bb4de7723f542be5923b06c4d704370f0390e4ae9e1c833c8785644c1
      command:
        - bash 
        - /var/logging/bin/example.sh
      volumeMounts:
        - name: logging-pub
          mountPath: /var/logging/logging.pub
          readOnly: true
        - name: logging-bin
          mountPath: /var/logging/bin
          readOnly: true
  volumes:
    - name: logging-pub
      hostPath:
        path: ./logging.pub
        type: File
    - name: logging-bin
      hostPath:
        path: ./bin/
        type: Directory
